import sqlalchemy_utils.types
import sqlalchemy_utils
#
# This file is part of Invenio.
# Copyright (C) 2016-2018 CERN.
#
# Invenio is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.

"""nrp install revision."""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'af481b685ce7'
down_revision = '3228b523dbbe'
branch_labels = ()
depends_on = None


def upgrade():
    """Upgrade database."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nrdocuments_parent_metadata',
    sa.Column('created', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=False),
    sa.Column('updated', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=False),
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('json', sa.JSON().with_variant(sqlalchemy_utils.types.json.JSONType(), 'mysql').with_variant(postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), 'postgresql').with_variant(sqlalchemy_utils.types.json.JSONType(), 'sqlite'), nullable=True),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_nrdocuments_parent_metadata'))
    )
    op.drop_table('nr_documents_parent_metadata')
    op.drop_constraint('fk_nrdocuments_metadata_parent_id_nr_documents_parent_metadata', 'nrdocuments_metadata', type_='foreignkey')
    op.create_foreign_key(op.f('fk_nrdocuments_metadata_parent_id_nrdocuments_parent_metadata'), 'nrdocuments_metadata', 'nrdocuments_parent_metadata', ['parent_id'], ['id'], ondelete='RESTRICT')
    op.drop_constraint('fk_nrdocumentsdraft_metadata_parent_id_nr_documents_par_1588', 'nrdocumentsdraft_metadata', type_='foreignkey')
    op.create_foreign_key(op.f('fk_nrdocumentsdraft_metadata_parent_id_nrdocuments_parent_metadata'), 'nrdocumentsdraft_metadata', 'nrdocuments_parent_metadata', ['parent_id'], ['id'], ondelete='RESTRICT')
    op.drop_constraint('fk_parent_state_parent_id_nr_documents_parent_metadata', 'parent_state', type_='foreignkey')
    op.create_foreign_key(op.f('fk_parent_state_parent_id_nrdocuments_parent_metadata'), 'parent_state', 'nrdocuments_parent_metadata', ['parent_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    """Downgrade database."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_parent_state_parent_id_nrdocuments_parent_metadata'), 'parent_state', type_='foreignkey')
    op.create_foreign_key('fk_parent_state_parent_id_nr_documents_parent_metadata', 'parent_state', 'nr_documents_parent_metadata', ['parent_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('fk_nrdocumentsdraft_metadata_parent_id_nrdocuments_parent_metadata'), 'nrdocumentsdraft_metadata', type_='foreignkey')
    op.create_foreign_key('fk_nrdocumentsdraft_metadata_parent_id_nr_documents_par_1588', 'nrdocumentsdraft_metadata', 'nr_documents_parent_metadata', ['parent_id'], ['id'], ondelete='RESTRICT')
    op.drop_constraint(op.f('fk_nrdocuments_metadata_parent_id_nrdocuments_parent_metadata'), 'nrdocuments_metadata', type_='foreignkey')
    op.create_foreign_key('fk_nrdocuments_metadata_parent_id_nr_documents_parent_metadata', 'nrdocuments_metadata', 'nr_documents_parent_metadata', ['parent_id'], ['id'], ondelete='RESTRICT')
    op.create_table('nr_documents_parent_metadata',
    sa.Column('created', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('json', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('version_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='pk_nr_documents_parent_metadata')
    )
    op.drop_table('nrdocuments_parent_metadata')
    # ### end Alembic commands ###
