import sqlalchemy_utils.types
import sqlalchemy_utils
#
# This file is part of Invenio.
# Copyright (C) 2016-2018 CERN.
#
# Invenio is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.

"""Initial revision."""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'nr_documents_2'
down_revision = 'nr_documents_1'
branch_labels = ()
depends_on = None


def upgrade():
    """Upgrade database."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nr_documents_metadata_version',
    sa.Column('created', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), autoincrement=False, nullable=False),
    sa.Column('updated', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), autoincrement=False, nullable=False),
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(), autoincrement=False, nullable=False),
    sa.Column('json', sa.JSON().with_variant(sqlalchemy_utils.types.json.JSONType(), 'mysql').with_variant(postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), 'postgresql').with_variant(sqlalchemy_utils.types.json.JSONType(), 'sqlite'), autoincrement=False, nullable=True),
    sa.Column('version_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('index', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('parent_id', sqlalchemy_utils.types.uuid.UUIDType(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id', name=op.f('pk_nr_documents_metadata_version'))
    )
    op.create_index(op.f('ix_nr_documents_metadata_version_end_transaction_id'), 'nr_documents_metadata_version', ['end_transaction_id'], unique=False)
    op.create_index(op.f('ix_nr_documents_metadata_version_operation_type'), 'nr_documents_metadata_version', ['operation_type'], unique=False)
    op.create_index(op.f('ix_nr_documents_metadata_version_transaction_id'), 'nr_documents_metadata_version', ['transaction_id'], unique=False)
    op.create_table('nr_documents_parent_record_metadata',
    sa.Column('created', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=False),
    sa.Column('updated', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=False),
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('json', sa.JSON().with_variant(sqlalchemy_utils.types.json.JSONType(), 'mysql').with_variant(postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), 'postgresql').with_variant(sqlalchemy_utils.types.json.JSONType(), 'sqlite'), nullable=True),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_nr_documents_parent_record_metadata'))
    )
    op.create_table('nr_documents_draft_metadata',
    sa.Column('created', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=False),
    sa.Column('updated', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=False),
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('json', sa.JSON().with_variant(sqlalchemy_utils.types.json.JSONType(), 'mysql').with_variant(postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), 'postgresql').with_variant(sqlalchemy_utils.types.json.JSONType(), 'sqlite'), nullable=True),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('index', sa.Integer(), nullable=True),
    sa.Column('fork_version_id', sa.Integer(), nullable=True),
    sa.Column('expires_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=True),
    sa.Column('parent_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['nr_documents_parent_record_metadata.id'], name=op.f('fk_nr_documents_draft_metadata_parent_id_nr_documents_parent_record_metadata'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_nr_documents_draft_metadata'))
    )
    op.create_table('nr_documents_metadata',
    sa.Column('created', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=False),
    sa.Column('updated', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=False),
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('json', sa.JSON().with_variant(sqlalchemy_utils.types.json.JSONType(), 'mysql').with_variant(postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), 'postgresql').with_variant(sqlalchemy_utils.types.json.JSONType(), 'sqlite'), nullable=True),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('index', sa.Integer(), nullable=True),
    sa.Column('parent_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['nr_documents_parent_record_metadata.id'], name=op.f('fk_nr_documents_metadata_parent_id_nr_documents_parent_record_metadata'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_nr_documents_metadata'))
    )
    op.create_table('nr_documents_parent_state',
    sa.Column('latest_index', sa.Integer(), nullable=True),
    sa.Column('parent_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('latest_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.Column('next_draft_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.ForeignKeyConstraint(['latest_id'], ['nr_documents_metadata.id'], name=op.f('fk_nr_documents_parent_state_latest_id_nr_documents_metadata')),
    sa.ForeignKeyConstraint(['next_draft_id'], ['nr_documents_draft_metadata.id'], name=op.f('fk_nr_documents_parent_state_next_draft_id_nr_documents_draft_metadata')),
    sa.ForeignKeyConstraint(['parent_id'], ['nr_documents_parent_record_metadata.id'], name=op.f('fk_nr_documents_parent_state_parent_id_nr_documents_parent_record_metadata'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('parent_id', name=op.f('pk_nr_documents_parent_state'))
    )
    op.drop_index('ix_uq_partial_files_object_is_head', table_name='files_object')
    op.alter_column('oaibatch_metadata_version', 'created',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               autoincrement=False)
    op.alter_column('oaibatch_metadata_version', 'updated',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               autoincrement=False)
    op.alter_column('oaibatch_metadata_version', 'version_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=False)
    op.alter_column('oaiharvester_metadata_version', 'created',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               autoincrement=False)
    op.alter_column('oaiharvester_metadata_version', 'updated',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               autoincrement=False)
    op.alter_column('oaiharvester_metadata_version', 'version_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=False)
    op.alter_column('oairecord_metadata_version', 'created',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               autoincrement=False)
    op.alter_column('oairecord_metadata_version', 'updated',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               autoincrement=False)
    op.alter_column('oairecord_metadata_version', 'version_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=False)
    op.alter_column('oairun_metadata_version', 'created',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               autoincrement=False)
    op.alter_column('oairun_metadata_version', 'updated',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               autoincrement=False)
    op.alter_column('oairun_metadata_version', 'version_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=False)
    # ### end Alembic commands ###


def downgrade():
    """Downgrade database."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('oairun_metadata_version', 'version_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=False)
    op.alter_column('oairun_metadata_version', 'updated',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               autoincrement=False)
    op.alter_column('oairun_metadata_version', 'created',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               autoincrement=False)
    op.alter_column('oairecord_metadata_version', 'version_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=False)
    op.alter_column('oairecord_metadata_version', 'updated',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               autoincrement=False)
    op.alter_column('oairecord_metadata_version', 'created',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               autoincrement=False)
    op.alter_column('oaiharvester_metadata_version', 'version_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=False)
    op.alter_column('oaiharvester_metadata_version', 'updated',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               autoincrement=False)
    op.alter_column('oaiharvester_metadata_version', 'created',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               autoincrement=False)
    op.alter_column('oaibatch_metadata_version', 'version_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=False)
    op.alter_column('oaibatch_metadata_version', 'updated',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               autoincrement=False)
    op.alter_column('oaibatch_metadata_version', 'created',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               autoincrement=False)
    op.create_index('ix_uq_partial_files_object_is_head', 'files_object', ['bucket_id', 'key'], unique=False)
    op.drop_table('nr_documents_parent_state')
    op.drop_table('nr_documents_metadata')
    op.drop_table('nr_documents_draft_metadata')
    op.drop_table('nr_documents_parent_record_metadata')
    op.drop_index(op.f('ix_nr_documents_metadata_version_transaction_id'), table_name='nr_documents_metadata_version')
    op.drop_index(op.f('ix_nr_documents_metadata_version_operation_type'), table_name='nr_documents_metadata_version')
    op.drop_index(op.f('ix_nr_documents_metadata_version_end_transaction_id'), table_name='nr_documents_metadata_version')
    op.drop_table('nr_documents_metadata_version')
    # ### end Alembic commands ###
