import sqlalchemy_utils.types
import sqlalchemy_utils
#
# This file is part of Invenio.
# Copyright (C) 2016-2018 CERN.
#
# Invenio is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.

"""Nrp install revision."""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'nr_documents_4'
down_revision = 'nr_documents_3'
branch_labels = ()
depends_on = None


def upgrade():
    """Upgrade database."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nr_documents_file_draft_metadata',
    sa.Column('created', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=False),
    sa.Column('updated', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=False),
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('json', sa.JSON().with_variant(sqlalchemy_utils.types.json.JSONType(), 'mysql').with_variant(postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), 'postgresql').with_variant(sqlalchemy_utils.types.json.JSONType(), 'sqlite'), nullable=True),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.Text().with_variant(mysql.VARCHAR(length=255), 'mysql'), nullable=False),
    sa.Column('record_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('object_version_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.ForeignKeyConstraint(['object_version_id'], ['files_object.version_id'], name=op.f('fk_nr_documents_file_draft_metadata_object_version_id_files_object'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['record_id'], ['nr_documents_draft_metadata.id'], name=op.f('fk_nr_documents_file_draft_metadata_record_id_nr_documents_draft_metadata'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_nr_documents_file_draft_metadata'))
    )
    op.create_index('uidx_nr_documents_file_draft_metadata_id_key', 'nr_documents_file_draft_metadata', ['id', 'key'], unique=True)
    op.create_table('nr_documents_file_metadata',
    sa.Column('created', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=False),
    sa.Column('updated', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=False),
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('json', sa.JSON().with_variant(sqlalchemy_utils.types.json.JSONType(), 'mysql').with_variant(postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), 'postgresql').with_variant(sqlalchemy_utils.types.json.JSONType(), 'sqlite'), nullable=True),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.Text().with_variant(mysql.VARCHAR(length=255), 'mysql'), nullable=False),
    sa.Column('record_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('object_version_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.ForeignKeyConstraint(['object_version_id'], ['files_object.version_id'], name=op.f('fk_nr_documents_file_metadata_object_version_id_files_object'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['record_id'], ['nr_documents_metadata.id'], name=op.f('fk_nr_documents_file_metadata_record_id_nr_documents_metadata'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_nr_documents_file_metadata'))
    )
    op.create_index('uidx_nr_documents_file_metadata_id_key', 'nr_documents_file_metadata', ['id', 'key'], unique=True)
    op.drop_index('ix_uq_partial_files_object_is_head', table_name='files_object')
    op.add_column('nr_documents_draft_metadata', sa.Column('bucket_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True))
    op.create_foreign_key(op.f('fk_nr_documents_draft_metadata_bucket_id_files_bucket'), 'nr_documents_draft_metadata', 'files_bucket', ['bucket_id'], ['id'])
    op.add_column('nr_documents_metadata', sa.Column('bucket_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True))
    op.create_foreign_key(op.f('fk_nr_documents_metadata_bucket_id_files_bucket'), 'nr_documents_metadata', 'files_bucket', ['bucket_id'], ['id'])
    op.add_column('nr_documents_metadata_version', sa.Column('bucket_id', sqlalchemy_utils.types.uuid.UUIDType(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###


def downgrade():
    """Downgrade database."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('nr_documents_metadata_version', 'bucket_id')
    op.drop_constraint(op.f('fk_nr_documents_metadata_bucket_id_files_bucket'), 'nr_documents_metadata', type_='foreignkey')
    op.drop_column('nr_documents_metadata', 'bucket_id')
    op.drop_constraint(op.f('fk_nr_documents_draft_metadata_bucket_id_files_bucket'), 'nr_documents_draft_metadata', type_='foreignkey')
    op.drop_column('nr_documents_draft_metadata', 'bucket_id')
    op.create_index('ix_uq_partial_files_object_is_head', 'files_object', ['bucket_id', 'key'], unique=False)
    op.drop_index('uidx_nr_documents_file_metadata_id_key', table_name='nr_documents_file_metadata')
    op.drop_table('nr_documents_file_metadata')
    op.drop_index('uidx_nr_documents_file_draft_metadata_id_key', table_name='nr_documents_file_draft_metadata')
    op.drop_table('nr_documents_file_draft_metadata')
    # ### end Alembic commands ###
