#!/bin/bash

set -e

PYTHON="${PYTHON:-python3}"

# to find dynamic libraries (such as cairo, useful for MX Macs)
# export DYLD_FALLBACK_LIBRARY_PATH=/opt/homebrew/lib
#
if [ -f ~/.envrc.local ] ; then
  source ~/.envrc.local
fi

cli_directory=$(dirname "$0")/.venv/nrp

test -d "$cli_directory" || {
  $PYTHON -m venv "${cli_directory}"
  "${cli_directory}"/bin/pip install -U setuptools pip wheel
  "${cli_directory}"/bin/pip install oarepo-cli
}

source "$cli_directory"/bin/activate
"$cli_directory"/bin/nrp "$@"
