FROM oarepo/oarepo-base-production:11
LABEL maintainer="CESNET" \
    org.opencontainers.image.authors="Miroslav Bauer <bauer@cesnet.cz>" \
    org.opencontainers.image.title="NR Document Production repository image" \
    org.opencontainers.image.url="https://hub.docker.com/r/Narodni-repozitar/nr-docs" \
    org.opencontainers.image.source="https://github.com/Narodni-repozitar/nr-docs" \
    org.opencontainers.image.documentation="https://github.com/Narodni-repozitar/nr-docs"

ARG REPOSITORY_SITE_NAME

